adding Uptycs API backend
AbGuthrie/goquery pull request #127
Opened 2020-05-20 18:33 UTC by carlv-stripe

adds Uptycs API

2020-05-20 19:04 UTC, obelisk commented on api/uptycs/client.go
> +func credentials() (*uptycsConfig, error) {
You can customize the goquery config file and add other top level keys there to merge your configs into one.

Since this will build as it's own binary and you pass the config structure into the goquery library, you won't have to worry about breaking the config.

2020-05-20 19:04 UTC, obelisk commented on api/uptycs/client.go
> +		reqBytes, err := httputil.DumpRequest(req, true)
Break this out into it's own function and maybe control with a debug flag from the config file.

2020-05-20 19:04 UTC, obelisk commented on api/uptycs/client.go
> +		this is not a good way to get the current user, but it seemed like a
If you have a feature request from Uptycs with an ID we should link it here.

2020-05-20 19:04 UTC, obelisk commented on api/uptycs/client.go
> +	This is a dirty hack that will make memory expand per query due to its design.
If you have a feature request from Uptycs with an ID we should link it here.

2020-05-20 22:30 UTC, carlv-stripe commented on api/uptycs/client.go
> +	This is a dirty hack that will make memory expand per query due to its design.
I do not, also, it was not a feature request, I asked them about it internally and they have confirmed that it's coming at some point.

2020-05-20 22:31 UTC, carlv-stripe commented on api/uptycs/client.go
> +		this is not a good way to get the current user, but it seemed like a
I do not, I'm also not sure what the actual "right" way to do this as every fleet manager seems to do it differently. Am available to change if anybody has a better idea but so far this has been working for me

2020-05-21 04:49 UTC, AbGuthrie requested changes
Hi @carlv-stripe, thank you for the updated PR

A few minor comments here but overall looks good!

2020-05-21 04:49 UTC, AbGuthrie commented on api/uptycs/client.go
> +	retVal.httpClient = &http.Client{}
It's a good idea to set a `Timeout: time.Second * 10` to the client initialization in case the server is unreachable, it will avoid the application completely hanging

2020-05-21 04:49 UTC, AbGuthrie commented on examples/uptycs.go
> +	goquery.Run(api, cfg.GoqueryConfig)
Pass `cfg` in here?

2020-05-21 04:49 UTC, AbGuthrie commented on api/uptycs/client.go
> +func CreateUptycsAPI(cfg *GoqueryConfig) (models.GoQueryAPI, error) {
Let's simplify the signature here and just pass in `(uptCfgPath string, debugEnabled bool)`. No need to worry about `GoqueryConfig config.Config` in this module.

2020-05-21 04:49 UTC, AbGuthrie commented on api/uptycs/client.go
> +func debugHTTPResponse(resp *http.Response) {
Nice, I like it

2020-05-26 14:59 UTC, carlv-stripe commented on examples/uptycs.go
> +	goquery.Run(api, cfg.GoqueryConfig)
I'm not sure what this means

2020-05-27 03:37 UTC, merged

2020-05-27 03:37 UTC, AbGuthrie commented
Nice one, thanks for that!

2020-06-12 14:52 UTC, gross-uptycs commented
This is awesome :) Thanks @carlv-stripe